<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>6.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Carbon">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\carbon\managed\Carbon.dll</HintPath>
    </Reference>
    <Reference Include="Carbon.Common">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\carbon\managed\Carbon.Common.dll</HintPath>
    </Reference>
    <Reference Include="Carbon.Compat">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\carbon\managed\Carbon.Compat.dll</HintPath>
    </Reference>
    <Reference Include="Carbon.SDK">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\carbon\managed\Carbon.SDK.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Console">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Facepunch.Console.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Network">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Facepunch.Network.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.System">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Facepunch.System.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.Unity">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Facepunch.Unity.dll</HintPath>
    </Reference>
    <Reference Include="Facepunch.UnityEngine">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Facepunch.UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Data">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Rust.Data.dll</HintPath>
    </Reference>
    <Reference Include="Rust.Global">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Rust.Global.dll</HintPath>
    </Reference>
    <Reference Include="Rust.UI">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\Rust.UI.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\..\..\..\..\..\rustserver_carbon\RustDedicated_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
